config/routes.rb
Rails.application.routes.draw do
  # To restrict routes later use: https://guides.rubyonrails.org/routing.html#restricting-the-routes-created
  root   'home#index'
  resources :categories
  resources :courses
  resources :coordinators
  resources :locations
  get    '/signup',  to: 'coordinators#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get    '/contact', to: 'contact#index'
  post   '/contact', to: 'contact#send_email'

  post '/courses/vote', to: 'votes#upsert', as: 'votes'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/coordinator.rb
class Coordinator < ApplicationRecord
    has_many :votes
    has_many :courses

    validates :name,
        presence: true,
        length: { minimum: 4 }
    
    validates :email,
        presence: true,
        length: { minimum: 4 },
        uniqueness: { case_sensitive: false },
        format: {
            with: /\A\w+\.\w+@rmit.edu.au\z/i,
            message: "Registration is only open to RMIT coordinators"
        }
    
    validates :password,
        presence: true,
        format: {
            with: /\A^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}/,
            message: "Password must contain at least: lowercase and uppercase letters, digits, special chars and a length of 8+"
        }

    validates :password_confirmation,
        presence: true

    has_secure_password

end

app/controllers/coordinators_controller.rb
class CoordinatorsController < ApplicationController
  before_action :set_coordinator, only: [:show, :edit, :update, :destroy]

  # GET /coordinators
  # GET /coordinators.json
  def index
    @coordinators = Coordinator.all
  end

  # GET /coordinators/1
  # GET /coordinators/1.json
  def show
  end

  # GET /coordinators/new
  def new
    @coordinator = Coordinator.new
  end

  # GET /coordinators/1/edit
  def edit
  end

  # POST /coordinators
  # POST /coordinators.json
  def create
    @coordinator = Coordinator.new(coordinator_params)

    respond_to do |format|
      if @coordinator.save
        log_in @coordinator
        format.html { redirect_to @coordinator, notice: 'Coordinator was successfully created.' }
        format.json { render :show, status: :created, location: @coordinator }
      else
        format.html { render :new }
        format.json { render json: @coordinator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coordinators/1
  # PATCH/PUT /coordinators/1.json
  def update
    respond_to do |format|
      if @coordinator.update(coordinator_params)
        format.html { redirect_to @coordinator, notice: 'Coordinator was successfully updated.' }
        format.json { render :show, status: :ok, location: @coordinator }
      else
        format.html { render :edit }
        format.json { render json: @coordinator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coordinators/1
  # DELETE /coordinators/1.json
  def destroy
    @coordinator.destroy
    respond_to do |format|
      format.html { redirect_to coordinators_url, notice: 'Coordinator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coordinator
      @coordinator = Coordinator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coordinator_params
      params.require(:coordinator).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/coordinators_helper.rb
module CoordinatorsHelper
    def gravatar_for(coordinator)
        gravatar_id = Digest::MD5::hexdigest(coordinator.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: coordinator.name, class: "gravatar")
      end
end

app/views/coordinators/_form.html.erb
<%= form_with(model: coordinator, local: true) do |form| %>
  <% if coordinator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coordinator.errors.count, "error") %> prohibited this coordinator from being saved:</h2>

      <ul>
      <% coordinator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :coordinator_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, id: :coordinator_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :coordinator_password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :coordinator_password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coordinators/edit.html.erb
<h1>Editing Coordinator</h1>

<%= render 'form', coordinator: @coordinator %>

<%= link_to 'Show', @coordinator %> |
<%= link_to 'Back', coordinators_path %>

app/views/coordinators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coordinators</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coordinators.each do |coordinator| %>
      <tr>
        <td><%= coordinator.name %></td>
        <td><%= coordinator.email %></td>
        <td><%= coordinator.password %></td>
        <td><%= link_to 'Show', coordinator %></td>
        <td><%= link_to 'Edit', edit_coordinator_path(coordinator) %></td>
        <td><%= link_to 'Destroy', coordinator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coordinator', new_coordinator_path %>

app/views/coordinators/new.html.erb
<h1>Signup</h1>

<%= render 'form', coordinator: @coordinator %>

app/views/coordinators/show.html.erb
<p id="notice"></p>

<div class="row">
<div class="col-xs-4 col-xs-offset-4">
  <div class="edit-image">
    <%= gravatar_for @coordinator %>
  </div>
  <h5 class="center">
    <strong>Name:</strong>
    <%= @coordinator.name %>
  </h5>

  <h5 class="center">
    <strong>Email:</strong>
    <%= @coordinator.email %>
  </h5>
</div>
<div class="clearfix"></div>
</div>
<hr>
<br>

<div class="row">
  <% @coordinator.courses.each do |course| %>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= course.name %></h3>
        </div>
        <%= image_tag course.image, class: "course-image" %>
        <div class="panel-body">
          <p><%= course.description %></p>
          <p>
            <b>Prerequisites: </b>
            <%= course.prerequisites %>
          </p>
          <p class = "small">Created: <%= time_since(course.updated_at) %> ago</p>
          <% if logged_in? %>
            <div class="button-panel">
              <div class="pull-left">
                <%= link_to votes_path(is_positive: true, course_id: course.id, coordinator_id: current_coordinator.id), method: :post, class: 'btn btn-success', title: 'Positive vote' do %>
                  &uarr; <%= Vote.where(course_id: course.id, is_positive: true).count %>
                <% end %>

                <%= link_to votes_path(is_positive: false, course_id: course.id, coordinator_id: current_coordinator.id), method: :post, class: 'btn btn-danger', title: 'Negative vote' do %>
                  &darr; <%= Vote.where(course_id: course.id, is_positive: false).count %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>