config/routes.rb
Rails.application.routes.draw do
  # To restrict routes later use: https://guides.rubyonrails.org/routing.html#restricting-the-routes-created
  root   'home#index'
  resources :categories
  resources :courses
  resources :coordinators
  resources :locations
  get    '/signup',  to: 'coordinators#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get    '/contact', to: 'contact#index'
  post   '/contact', to: 'contact#send_email'

  post '/courses/vote', to: 'votes#upsert', as: 'votes'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_coordinator_panel.html.erb
<div class="col-md-4">
  <div class="thumbnail">
    <div class="row">
      <div class="col-md-3 coordinator-thumbnail">
        <%= gravatar_for coordinator %>
      </div>
      <div class="col-md-7 coordinator-caption">
        <div class="caption">
          <h4><%= coordinator.name %></h4>
          <p><%= coordinator.email %></p>
        </div>
      </div>      
    </div>
  </div>
</div>

app/views/shared/_course_panel.html.erb
<div class="col-md-4">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= course.name %></h3>
    </div>
    <%= image_tag course.image, class: "course-image" %>
    <div class="panel-body">
      <p><%= course.description %></p>
      <p>
        <b>Prerequisites: </b>
        <%= course.prerequisites %>
      </p>
      <p>
        <b>Locations: </b>
        <% course.locations.each do |location| %>
          <%= link_to location_path(location) do %>
            <%= location.code %>
            <% end %>
          <% if location != course.locations.last %>, <% end %>
        <% end %>
      </p>
      <p>
        <b>Categories: </b>
        <% course.categories.each do |category| %>
          <%= link_to category_path(category) do %>
            <%= category.name %>
          <% end %>
          <% if category != course.categories.last %>, <% end %>
        <% end %>
      </p>
      <p class = "small">Created: <%= time_since(course.updated_at) %> ago</p>
      <% if logged_in? %>
        <div class="button-panel">
          <div class="pull-left">
            <%= link_to votes_path(is_positive: true, course_id: course.id, coordinator_id: current_coordinator.id), method: :post, class: 'btn btn-success', title: 'Positive vote' do %>
              &uarr; <%= Vote.where(course_id: course.id, is_positive: true).count %>
            <% end %>

            <%= link_to votes_path(is_positive: false, course_id: course.id, coordinator_id: current_coordinator.id), method: :post, class: 'btn btn-danger', title: 'Negative vote' do %>
              &darr; <%= Vote.where(course_id: course.id, is_positive: false).count %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>