config/routes.rb
Rails.application.routes.draw do
  # To restrict routes later use: https://guides.rubyonrails.org/routing.html#restricting-the-routes-created
  root   'home#index'
  resources :categories
  resources :courses
  resources :coordinators
  resources :locations
  get    '/signup',  to: 'coordinators#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get    '/contact', to: 'contact#index'
  post   '/contact', to: 'contact#send_email'

  post '/courses/vote', to: 'votes#upsert', as: 'votes'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_alert.html.erb
<% if flash.any? %>
  <% flash.each do |type, message| %>
    <div class="alert alert-<%= type %>"><%= message %></div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <%= link_to "/contact" do %>
    Contact us
  <% end %>|
  <%= link_to "https://www.rmit.edu.au" do %>
    RMIT
  <% end %>
  <small>
    By Aleksandar Stefanovic
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if logged_in? %> 
            <%= link_to "Home", courses_path %>
          <% else %> 
            <%= link_to "Home", root_path %>
          <% end %>
        </li>
        <li><%= link_to "Courses", courses_path %></li>
        <li>
          <a href="/categories" class="dropdown-toggle" data-toggle="dropdown" role="button">
            Categories <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <% Category.all.each do |category| %>
              <li><%= link_to category.name, category %></li>
            <% end %>
            <% if (Category.all.count > 0) %>
              <li role="separator" class="divider"></li>
            <% end %>
            <li><%= link_to 'All Categories', categories_path %></li>            
            <% if logged_in? %>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Create Category', new_category_path %></li>
            <% end %>
          </ul>
        </li>
        <li>
          <a href="/locations" class="dropdown-toggle" data-toggle="dropdown" role="button">
            Locations <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <% Location.all.each do |location| %>
              <li><%= link_to location.code, location %></li>
            <% end %>
            <% if (Location.all.count > 0) %>
              <li role="separator" class="divider"></li>
            <% end %>
            <li><%= link_to 'All Locations', locations_path %></li>            
            <% if logged_in? %>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Create Location', new_location_path %></li>
            <% end %>
          </ul>
        </li>
        
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_coordinator %></li>
              <li><%= link_to "Edit Profile", edit_coordinator_path(current_coordinator) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Course Management Application</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/alert' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>